---
name: AssetsOverview
---

SilverStripe\AssetAdmin\Controller\AssetAdmin:
  extensions:
    - 'Sunnysideup\AssetsOverview\Control\AssetAdminExtension'

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.assetsoverview:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "assetsoverview"
