---
name: AssetsOverview
---

SilverStripe\AssetAdmin\Controller\AssetAdmin:
    extensions:
        - 'Sunnysideup\AssetsOverview\Control\AssetAdminExtension'

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.myCache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "assetoverview"
